site_name: Siddhi Map Protobuf
site_description: Siddhi Map Protobuf Extension
site_author:
site_url:
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
repo_name: Siddhi-Map-Protobuf
repo_url:
copyright:
theme:
  name: 'material'
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
extra:
  social:
markdown_extensions:
  - admonition
  - toc(permalink=true)
  - codehilite(guess_lang=false)
pages:
  - Welcome : index.md
  - API Docs:
      - 1.0.0-SNAPSHOT: api/1.0.0-SNAPSHOT.md
  - License: about/license.md
